### ISSUE TITLE
Tail Call

### ISSUE THREAD

**Issue by fgmccabe** [zherczeg/sljit#44]
I am trying to decide if sljit is for me. One of the questions I have is if sljit can support tail calls; and if not how much work would it be to support?

Note: My requirement is to be able to tail call into arbitrary functions; not special tail callable functions (as in lightning)

**Comment by zherczeg** [comment]
This is definitely an interesting topic. The issue with tail calling is stack management. If an argument needs to be passed on a stack (e.g. a floating point argument), then the called function has no idea that it should clean up the stack. Anyway you can definitely tail call to functions which arguments are passed only in registers. Probably the most difficult architecture is x86-32, where no arguments are passed in registers except when "fastcall" calling convention is used (and even in that case, only two registers can be used for passing arguments). Currently sljit has no tail call interface, but adding one with the limitations above would be possible. Intel Control-flow Enforcement Technology support should be supported in some way as well.

You also have another option called fast calls. That is a unique caling convention in sljit, which allows executing code in the same stack context as the caller. You just need to preserve the return value somewhere. You can chain them in any way you want, even skipping some returns.

**Comment by fgmccabe** [comment]
There are two principal ways of implementing full tail call. The first 'conventional' way is to implement what is essentially a 'return followed by a call'; the second is to garbage collect the stack. I would guess that the second approach is not feasible for sljit.
The first is though. The callee does not need to know anything about the caller; what happens is that you perform all the actions you would for a return from the current function; and then enter the callee. It does not make a material difference where your arguments are -- except that you have to know. I.e., the caller must know where its arguments are.

In fact, the hardest issue to deal with is not register arguments but the local stack. Tail call amounts to a stack slide: the arguments of the call are slid up the stack to overwrite the caller's arguments (whilst keeping track of return pointer and frame pointer) Since sljit is 'stackless' I guess that means that the programmer would need to know and give guidance to sljit.

Since I do not fully grok sljit at the moment (its an investment I am contemplating) I don't know how hard it would be.

My use case is compiling a VM that relies heavily on tail calls (and other things like GC but that is different).

(Actually, there are some interesting ideas about that too)

**Comment by zherczeg** [comment]
I am not sure I follow. Let;s we have three functions, A, B and C. A calls B, then B tail calls C, so when C returns, it returns to A instead of B. To do that, B needs to do the following steps:

- Restore the saved registers and clean up the stack (this is basically the return instruction)
- Use a jump instruction instead of a call instruction to call C (so return to B never happens)
- If the return address is in a register on the current CPU, that needs to be restored as well, since C needs it to return to A. This will automatically happen during the first step.

I suspect this is the "conventional" way. I don't know the "garbage collecting" technique.

The problem is the arguments. As long as the arguments are in registers, they are simple discarded after C. However, if some arguments needs to be on the stack, that means stack needs to be allocated for them. According to the C standard, B needs to manage this stack for efficiency reasons: it can reuse it for several function calls without reallocating it. This means C will never cleans up this stack, and this will cause problem.

With fast calls, your entire prgram can be a single function call, where various routines share the same function context. This is perfect for tail calls as long as you control the whole environment.

**Comment by fgmccabe** [comment]
To execute a tail call you have to discard the arguments of the current call while preserving anything needed for the new callee. Note that tail call is not possible if the callee has a reference to anything in the call.
To be discarded: all the locals of the current call, and all the arguments of the current call.
To be preserved: all the arguments of the callee.
To be preserved: return pointer of the current call
To be preserved: recorded frame pointer (it would normally be restored on a return)
If none of the arguments of either the current function or the callee are in registers then you have to 'slide' the arguments of the callee to where the current call has them. This slide could be in either direction: if the callee has more arguments than the current call then the activation record will be moved down (assuming stack grows down in memory). If the callee has fewer arguments than the current function then the activation will be moved up.
Any arguments that are in registers can be ignored as you noted.

Note: it can be useful to temporarily regard the return address and frame pointer as 'extra arguments' -- this simplifies the overall approach.

BTW: your fast call mechanism is probably not that relevant to me. I have heard others refer to this concept as 'leaf calls' : the callee does not itself call anything.

**Comment by zherczeg** [comment]
Here is an x86-64 source code, compiled by gcc with -O3:
```
int called1(int arg1, int arg2);

int caller1()
{
  return called1(1, 2);
}

int called2(int arg1, int arg2, int arg3, int arg4,
  int arg5, int arg6, int arg7, int arg8);

int caller2()
{
  return called2(1, 2, 3, 4, 5, 6, 7, 8);
}
```
The generated assembly dump is the following:
```
0000000000000000 <caller1>:
   0:   be 02 00 00 00          mov    $0x2,%esi
   5:   bf 01 00 00 00          mov    $0x1,%edi
   a:   e9 00 00 00 00          jmpq   f <caller1+0xf>
   f:   90                      nop

0000000000000010 <caller2>:
  10:   48 83 ec 18             sub    $0x18,%rsp
  14:   41 b9 06 00 00 00       mov    $0x6,%r9d
  1a:   41 b8 05 00 00 00       mov    $0x5,%r8d
  20:   c7 44 24 08 08 00 00    movl   $0x8,0x8(%rsp)
  27:   00
  28:   c7 04 24 07 00 00 00    movl   $0x7,(%rsp)
  2f:   b9 04 00 00 00          mov    $0x4,%ecx
  34:   ba 03 00 00 00          mov    $0x3,%edx
  39:   be 02 00 00 00          mov    $0x2,%esi
  3e:   bf 01 00 00 00          mov    $0x1,%edi
  43:   e8 00 00 00 00          callq  48 <caller2+0x38>
  48:   48 83 c4 18             add    $0x18,%rsp
  4c:   c3                      retq
```

In the first case it uses a tail call with a jump instruction. However in the second it cannot use that, because two arguments are passed on the stack.

This is the x86-32 assembly dump of the first function:
```
00000000 <caller1>:
   0:   83 ec 1c                sub    $0x1c,%esp
   3:   c7 44 24 04 02 00 00    movl   $0x2,0x4(%esp)
   a:   00
   b:   c7 04 24 01 00 00 00    movl   $0x1,(%esp)
  12:   e8 fc ff ff ff          call   13 <caller1+0x13>
  17:   83 c4 1c                add    $0x1c,%esp
  1a:   c3                      ret
```
Since no arguments are passed in registers, even in this simple case it cannot use tail call. Except if no paramters are passed:
```
int called1();

int caller1()
{
  return called1();
}

00000000 <caller1>:
   0:   e9 fc ff ff ff          jmp    1 <caller1+0x1>
```
If I change called1 to fastcall, it can use tail call but only with maximum of two arguments:
```
__attribute__ ((fastcall)) int called1(int arg1, int arg2);

00000000 <caller1>:
   0:   ba 02 00 00 00          mov    $0x2,%edx
   5:   b9 01 00 00 00          mov    $0x1,%ecx
   a:   e9 fc ff ff ff          jmp    b <caller1+0xb>
```
I don't see any argument 'sliding'. Am I missing something?

**Comment by fgmccabe** [comment]
Ah yes. In C, tail call is an 'optimization'; gcc in particular is quite conservative about it. Not sure that clang is that much better.
For some languages, (including Prolog, Scheme, ML, and also my personal language Star -- which is what I want to compile) tail call is part of the semantics.
WebAssembly has tail call too; not as an optimization but as a special instruction: return_call.
Javascript had it briefly -- as an optimization. But it confused too many people so it was removed.

**Comment by zherczeg** [comment]
I did some extra testing, and noticed that gcc does tail call if the called function requires less or equal stack space than the caller on x86. I suspect these rules are defined by the Application Binary Interface (ABI), and gcc simply follows it. Anyway sljit is low-level, and can follow any ABI. It just needs to be defined what should exactly happen on each supported architecture.

**Comment by fgmccabe** [comment]
I think that tail call per se is not defined in your typical API doc. I just looked at Intel's ABI [https://www.uclibc.org/docs/psABI-i386.pdf](url). It does not mention tail call. On the other hand, it is sufficiently detailed that you could safely implement tail call while respecting it. I am not at all familiar with ARM (though I expect to be in the years to come ..)

**Comment by zherczeg** [comment]
Taill call is supported now except sparc (todo). If tail call is not possible because of arguments, stack is still reduced.
